### ISSUE TITLE
Initial checks required

### ISSUE THREAD

**Issue by 0xbadshah** [NullArray/IntRec-Pack#3]
The script heavily uses some external commands like: `wget`, `pip` and `sudo`
These commands - if not present - create error but *doesnt stop the installation*
For example,
```
 [+] Installing remaining dependencies. 

sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found
sudo: pip: command not found

 [+] All operations completed. 
```
Some Linux based OS (like Debian minimal) doesnt contain commands like `sudo` and `wget` by default.
So it is better to have a check in the script if the commands exist. Also writing about these dependencies explicitly on readme also makes sense.

**Comment by NullArray** [comment]
Good points, I will add these checks to the script and add something to facilitate to auto-resolving of these issues, i will also add some logic to see if the script is started as root for convenience sake.

**Comment by NullArray** [comment]
Added checks, added root check at start up.

https://github.com/NullArray/IntRec-Pack/commit/00106ec29a919fc794868bc02ad762c9a537127c
